import { DeepPartial } from 'typeorm';
import { Region } from '../entities/region.entity';

export const REGION_SEEDS: DeepPartial<Region>[] = [
  { districtCode: '11110', city: '서울특별시', district: '종로구' },
  { districtCode: '11140', city: '서울특별시', district: '중구' },
  { districtCode: '11170', city: '서울특별시', district: '용산구' },
  { districtCode: '11200', city: '서울특별시', district: '성동구' },
  { districtCode: '11215', city: '서울특별시', district: '광진구' },
  { districtCode: '11230', city: '서울특별시', district: '동대문구' },
  { districtCode: '11260', city: '서울특별시', district: '중랑구' },
  { districtCode: '11290', city: '서울특별시', district: '성북구' },
  { districtCode: '11305', city: '서울특별시', district: '강북구' },
  { districtCode: '11320', city: '서울특별시', district: '도봉구' },
  { districtCode: '11350', city: '서울특별시', district: '노원구' },
  { districtCode: '11380', city: '서울특별시', district: '은평구' },
  { districtCode: '11410', city: '서울특별시', district: '서대문구' },
  { districtCode: '11440', city: '서울특별시', district: '마포구' },
  { districtCode: '11470', city: '서울특별시', district: '양천구' },
  { districtCode: '11500', city: '서울특별시', district: '강서구' },
  { districtCode: '11530', city: '서울특별시', district: '구로구' },
  { districtCode: '11545', city: '서울특별시', district: '금천구' },
  { districtCode: '11560', city: '서울특별시', district: '영등포구' },
  { districtCode: '11590', city: '서울특별시', district: '동작구' },
  { districtCode: '11620', city: '서울특별시', district: '관악구' },
  { districtCode: '11650', city: '서울특별시', district: '서초구' },
  { districtCode: '11680', city: '서울특별시', district: '강남구' },
  { districtCode: '11710', city: '서울특별시', district: '송파구' },
  { districtCode: '11740', city: '서울특별시', district: '강동구' },
  { districtCode: '26110', city: '부산광역시', district: '중구' },
  { districtCode: '26140', city: '부산광역시', district: '서구' },
  { districtCode: '26170', city: '부산광역시', district: '동구' },
  { districtCode: '26200', city: '부산광역시', district: '영도구' },
  { districtCode: '26230', city: '부산광역시', district: '부산진구' },
  { districtCode: '26260', city: '부산광역시', district: '동래구' },
  { districtCode: '26290', city: '부산광역시', district: '남구' },
  { districtCode: '26320', city: '부산광역시', district: '북구' },
  { districtCode: '26350', city: '부산광역시', district: '해운대구' },
  { districtCode: '26380', city: '부산광역시', district: '사하구' },
  { districtCode: '26410', city: '부산광역시', district: '금정구' },
  { districtCode: '26440', city: '부산광역시', district: '강서구' },
  { districtCode: '26470', city: '부산광역시', district: '연제구' },
  { districtCode: '26500', city: '부산광역시', district: '수영구' },
  { districtCode: '26530', city: '부산광역시', district: '사상구' },
  { districtCode: '26710', city: '부산광역시', district: '기장군' },
  { districtCode: '27110', city: '대구광역시', district: '중구' },
  { districtCode: '27140', city: '대구광역시', district: '동구' },
  { districtCode: '27170', city: '대구광역시', district: '서구' },
  { districtCode: '27200', city: '대구광역시', district: '남구' },
  { districtCode: '27230', city: '대구광역시', district: '북구' },
  { districtCode: '27260', city: '대구광역시', district: '수성구' },
  { districtCode: '27290', city: '대구광역시', district: '달서구' },
  { districtCode: '27710', city: '대구광역시', district: '달성군' },
  { districtCode: '27720', city: '대구광역시', district: '군위군' },
  { districtCode: '28110', city: '인천광역시', district: '중구' },
  { districtCode: '28140', city: '인천광역시', district: '동구' },
  { districtCode: '28177', city: '인천광역시', district: '미추홀구' },
  { districtCode: '28185', city: '인천광역시', district: '연수구' },
  { districtCode: '28200', city: '인천광역시', district: '남동구' },
  { districtCode: '28237', city: '인천광역시', district: '부평구' },
  { districtCode: '28245', city: '인천광역시', district: '계양구' },
  { districtCode: '28260', city: '인천광역시', district: '서구' },
  { districtCode: '28710', city: '인천광역시', district: '강화군' },
  { districtCode: '28720', city: '인천광역시', district: '옹진군' },
  { districtCode: '29110', city: '광주광역시', district: '동구' },
  { districtCode: '29140', city: '광주광역시', district: '서구' },
  { districtCode: '29155', city: '광주광역시', district: '남구' },
  { districtCode: '29170', city: '광주광역시', district: '북구' },
  { districtCode: '29200', city: '광주광역시', district: '광산구' },
  { districtCode: '30110', city: '대전광역시', district: '동구' },
  { districtCode: '30140', city: '대전광역시', district: '중구' },
  { districtCode: '30170', city: '대전광역시', district: '서구' },
  { districtCode: '30200', city: '대전광역시', district: '유성구' },
  { districtCode: '30230', city: '대전광역시', district: '대덕구' },
  { districtCode: '31110', city: '울산광역시', district: '중구' },
  { districtCode: '31140', city: '울산광역시', district: '남구' },
  { districtCode: '31170', city: '울산광역시', district: '동구' },
  { districtCode: '31200', city: '울산광역시', district: '북구' },
  { districtCode: '31710', city: '울산광역시', district: '울주군' },
  { districtCode: '36110', city: '세종특별자치시', district: '세종특별자치시' },
  { districtCode: '41111', city: '경기도', district: '수원시 장안구' },
  { districtCode: '41113', city: '경기도', district: '수원시 권선구' },
  { districtCode: '41115', city: '경기도', district: '수원시 팔달구' },
  { districtCode: '41117', city: '경기도', district: '수원시 영통구' },
  { districtCode: '41131', city: '경기도', district: '성남시 수정구' },
  { districtCode: '41133', city: '경기도', district: '성남시 중원구' },
  { districtCode: '41135', city: '경기도', district: '성남시 분당구' },
  { districtCode: '41150', city: '경기도', district: '의정부시' },
  { districtCode: '41171', city: '경기도', district: '안양시 만안구' },
  { districtCode: '41173', city: '경기도', district: '안양시 동안구' },
  { districtCode: '41192', city: '경기도', district: '부천시 원미구' },
  { districtCode: '41194', city: '경기도', district: '부천시 소사구' },
  { districtCode: '41196', city: '경기도', district: '부천시 오정구' },
  { districtCode: '41210', city: '경기도', district: '광명시' },
  { districtCode: '41220', city: '경기도', district: '평택시' },
  { districtCode: '41250', city: '경기도', district: '동두천시' },
  { districtCode: '41271', city: '경기도', district: '안산시 상록구' },
  { districtCode: '41273', city: '경기도', district: '안산시 단원구' },
  { districtCode: '41281', city: '경기도', district: '고양시 덕양구' },
  { districtCode: '41285', city: '경기도', district: '고양시 일산동구' },
  { districtCode: '41287', city: '경기도', district: '고양시 일산서구' },
  { districtCode: '41290', city: '경기도', district: '과천시' },
  { districtCode: '41310', city: '경기도', district: '구리시' },
  { districtCode: '41360', city: '경기도', district: '남양주시' },
  { districtCode: '41370', city: '경기도', district: '오산시' },
  { districtCode: '41390', city: '경기도', district: '시흥시' },
  { districtCode: '41410', city: '경기도', district: '군포시' },
  { districtCode: '41430', city: '경기도', district: '의왕시' },
  { districtCode: '41450', city: '경기도', district: '하남시' },
  { districtCode: '41461', city: '경기도', district: '용인시 처인구' },
  { districtCode: '41463', city: '경기도', district: '용인시 기흥구' },
  { districtCode: '41465', city: '경기도', district: '용인시 수지구' },
  { districtCode: '41480', city: '경기도', district: '파주시' },
  { districtCode: '41500', city: '경기도', district: '이천시' },
  { districtCode: '41550', city: '경기도', district: '안성시' },
  { districtCode: '41570', city: '경기도', district: '김포시' },
  { districtCode: '41590', city: '경기도', district: '화성시' },
  { districtCode: '41610', city: '경기도', district: '광주시' },
  { districtCode: '41630', city: '경기도', district: '양주시' },
  { districtCode: '41650', city: '경기도', district: '포천시' },
  { districtCode: '41670', city: '경기도', district: '여주시' },
  { districtCode: '41800', city: '경기도', district: '연천군' },
  { districtCode: '41820', city: '경기도', district: '가평군' },
  { districtCode: '41830', city: '경기도', district: '양평군' },
  { districtCode: '43111', city: '충청북도', district: '청주시 상당구' },
  { districtCode: '43112', city: '충청북도', district: '청주시 서원구' },
  { districtCode: '43113', city: '충청북도', district: '청주시 흥덕구' },
  { districtCode: '43114', city: '충청북도', district: '청주시 청원구' },
  { districtCode: '43130', city: '충청북도', district: '충주시' },
  { districtCode: '43150', city: '충청북도', district: '제천시' },
  { districtCode: '43720', city: '충청북도', district: '보은군' },
  { districtCode: '43730', city: '충청북도', district: '옥천군' },
  { districtCode: '43740', city: '충청북도', district: '영동군' },
  { districtCode: '43745', city: '충청북도', district: '증평군' },
  { districtCode: '43750', city: '충청북도', district: '진천군' },
  { districtCode: '43760', city: '충청북도', district: '괴산군' },
  { districtCode: '43770', city: '충청북도', district: '음성군' },
  { districtCode: '43800', city: '충청북도', district: '단양군' },
  { districtCode: '44131', city: '충청남도', district: '천안시 동남구' },
  { districtCode: '44133', city: '충청남도', district: '천안시 서북구' },
  { districtCode: '44150', city: '충청남도', district: '공주시' },
  { districtCode: '44180', city: '충청남도', district: '보령시' },
  { districtCode: '44200', city: '충청남도', district: '아산시' },
  { districtCode: '44210', city: '충청남도', district: '서산시' },
  { districtCode: '44230', city: '충청남도', district: '논산시' },
  { districtCode: '44250', city: '충청남도', district: '계룡시' },
  { districtCode: '44270', city: '충청남도', district: '당진시' },
  { districtCode: '44710', city: '충청남도', district: '금산군' },
  { districtCode: '44760', city: '충청남도', district: '부여군' },
  { districtCode: '44770', city: '충청남도', district: '서천군' },
  { districtCode: '44790', city: '충청남도', district: '청양군' },
  { districtCode: '44800', city: '충청남도', district: '홍성군' },
  { districtCode: '44810', city: '충청남도', district: '예산군' },
  { districtCode: '44825', city: '충청남도', district: '태안군' },
  { districtCode: '46110', city: '전라남도', district: '목포시' },
  { districtCode: '46130', city: '전라남도', district: '여수시' },
  { districtCode: '46150', city: '전라남도', district: '순천시' },
  { districtCode: '46170', city: '전라남도', district: '나주시' },
  { districtCode: '46230', city: '전라남도', district: '광양시' },
  { districtCode: '46710', city: '전라남도', district: '담양군' },
  { districtCode: '46720', city: '전라남도', district: '곡성군' },
  { districtCode: '46730', city: '전라남도', district: '구례군' },
  { districtCode: '46770', city: '전라남도', district: '고흥군' },
  { districtCode: '46780', city: '전라남도', district: '보성군' },
  { districtCode: '46790', city: '전라남도', district: '화순군' },
  { districtCode: '46800', city: '전라남도', district: '장흥군' },
  { districtCode: '46810', city: '전라남도', district: '강진군' },
  { districtCode: '46820', city: '전라남도', district: '해남군' },
  { districtCode: '46830', city: '전라남도', district: '영암군' },
  { districtCode: '46840', city: '전라남도', district: '무안군' },
  { districtCode: '46860', city: '전라남도', district: '함평군' },
  { districtCode: '46870', city: '전라남도', district: '영광군' },
  { districtCode: '46880', city: '전라남도', district: '장성군' },
  { districtCode: '46890', city: '전라남도', district: '완도군' },
  { districtCode: '46900', city: '전라남도', district: '진도군' },
  { districtCode: '46910', city: '전라남도', district: '신안군' },
  { districtCode: '47111', city: '경상북도', district: '포항시 남구' },
  { districtCode: '47113', city: '경상북도', district: '포항시 북구' },
  { districtCode: '47130', city: '경상북도', district: '경주시' },
  { districtCode: '47150', city: '경상북도', district: '김천시' },
  { districtCode: '47170', city: '경상북도', district: '안동시' },
  { districtCode: '47190', city: '경상북도', district: '구미시' },
  { districtCode: '47210', city: '경상북도', district: '영주시' },
  { districtCode: '47230', city: '경상북도', district: '영천시' },
  { districtCode: '47250', city: '경상북도', district: '상주시' },
  { districtCode: '47280', city: '경상북도', district: '문경시' },
  { districtCode: '47290', city: '경상북도', district: '경산시' },
  { districtCode: '47730', city: '경상북도', district: '의성군' },
  { districtCode: '47750', city: '경상북도', district: '청송군' },
  { districtCode: '47760', city: '경상북도', district: '영양군' },
  { districtCode: '47770', city: '경상북도', district: '영덕군' },
  { districtCode: '47820', city: '경상북도', district: '청도군' },
  { districtCode: '47830', city: '경상북도', district: '고령군' },
  { districtCode: '47840', city: '경상북도', district: '성주군' },
  { districtCode: '47850', city: '경상북도', district: '칠곡군' },
  { districtCode: '47900', city: '경상북도', district: '예천군' },
  { districtCode: '47920', city: '경상북도', district: '봉화군' },
  { districtCode: '47930', city: '경상북도', district: '울진군' },
  { districtCode: '47940', city: '경상북도', district: '울릉군' },
  { districtCode: '48121', city: '경상남도', district: '창원시 의창구' },
  { districtCode: '48123', city: '경상남도', district: '창원시 성산구' },
  { districtCode: '48125', city: '경상남도', district: '창원시 마산합포구' },
  { districtCode: '48127', city: '경상남도', district: '창원시 마산회원구' },
  { districtCode: '48129', city: '경상남도', district: '창원시 진해구' },
  { districtCode: '48170', city: '경상남도', district: '진주시' },
  { districtCode: '48220', city: '경상남도', district: '통영시' },
  { districtCode: '48240', city: '경상남도', district: '사천시' },
  { districtCode: '48250', city: '경상남도', district: '김해시' },
  { districtCode: '48270', city: '경상남도', district: '밀양시' },
  { districtCode: '48310', city: '경상남도', district: '거제시' },
  { districtCode: '48330', city: '경상남도', district: '양산시' },
  { districtCode: '48720', city: '경상남도', district: '의령군' },
  { districtCode: '48730', city: '경상남도', district: '함안군' },
  { districtCode: '48740', city: '경상남도', district: '창녕군' },
  { districtCode: '48820', city: '경상남도', district: '고성군' },
  { districtCode: '48840', city: '경상남도', district: '남해군' },
  { districtCode: '48850', city: '경상남도', district: '하동군' },
  { districtCode: '48860', city: '경상남도', district: '산청군' },
  { districtCode: '48870', city: '경상남도', district: '함양군' },
  { districtCode: '48880', city: '경상남도', district: '거창군' },
  { districtCode: '48890', city: '경상남도', district: '합천군' },
  { districtCode: '50110', city: '제주특별자치도', district: '제주시' },
  { districtCode: '50130', city: '제주특별자치도', district: '서귀포시' },
];
