export enum NotificationType {
  HONEYBEE_REPORTED = 'HONEYBEE_REPORTED',
  HONEYBEE_RESERVED = 'HONEYBEE_RESERVED',
  HONEYBEE_RESERVE_CANCELED = 'HONEYBEE_RESERVE_CANCELED',
  HONEYBEE_REMOVED = 'HONEYBEE_REMOVED',
}
