export enum ErrorType {
  /* common */
  INVALID_REQUEST = 'INVALID_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  INVALID_FILE_FORMAT = 'INVALID_FILE_FORMAT',

  /* auth */
  KAKAO_LOGIN_FAILED = 'KAKAO_LOGIN_FAILED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN',
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',

  /* member */
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  INVALID_INTEREST_AREA_COUNT = 'INVALID_INTEREST_AREA_COUNT',
  INVALID_REGION_CODE = 'INVALID_REGION_CODE',

  /* region */
  INVALID_REGION_DISTRICT_CODE = 'INVALID_REGION_DISTRICT_CODE',

  /* hive-report */
  HIVE_REPORT_NOT_FOUND = 'HIVE_REPORT_NOT_FOUND',
  ALREADY_UPLOADED_HIVE_REPORT = 'ALREADY_UPLOADED_HIVE_REPORT',
  MEMBER_AND_REPORTER_MISMATCH = 'MEMBER_AND_REPORTER_MISMATCH',
  ALREADY_REMOVED_HIVE_REPORT = 'ALREADY_REMOVED_HIVE_REPORT',

  /* openai */
  VISION_SERVICE_UNAVAILABLE = 'VISION_SERVICE_UNAVAILABLE',
  INVALID_VISION_RESPONSE = 'INVALID_VISION_RESPONSE',
  VISION_JSON_PARSE_ERROR = 'VISION_JSON_PARSE_ERROR',
  VISION_SCHEMA_MISMATCH = 'VISION_SCHEMA_MISMATCH',
}
