name: CI-CD

on:
    push:
        branches: [ 'main' ]
    pull_request:
        branches: [ 'main' ]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out Repository
                uses: actions/checkout@v2

            -   name: Use Node.js
                uses: actions/setup-node@v4.3.0
                with:
                    node-version: 20

            -   name: Install dependencies
                run: npm install

#            -   name: Echo Env File
#                run: echo ${{ secrets.ENV_FILE }} | base64 --decode > ./.env

            -   name: Build Docker image
                run: |
                    docker build -t beesafe .

            -   name: Login to Docker Hub
                uses: docker/login-action@v3.4.0
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD }}

            -   name: Push to Docker Hub
                run: |
                    docker tag beesafe ${{ secrets.DOCKERHUB_USERNAME }}/beesafe:latest
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/beesafe:latest